import { test, expect } from "@playwright/test";
import { baseline, worstCaseIds } from "../src/data";

test("fast-wave release controls support activation, disabling and saved configurations", async ({ page }) => {
  const s = baseline([worstCaseIds.fastest]);
  s.waves[0].start = 7200;
  s.worstCaseTeams.fastest.mode = "flat";
  s.worstCaseTeams.fastest.flatPace = 900;
  await page.goto("./");
  await page.getByLabel("Import configuration JSON").setInputFiles({ name: "later.json", mimeType: "application/json", buffer: Buffer.from(JSON.stringify(s)) });
  await page.getByRole("tab", { name: /Timing rules/ }).click();
  const enabled = page.getByLabel("Enable releases for fast waves", { exact: true });
  const exchange = page.getByLabel("Fast-wave release starting exchange", { exact: true });
  const count = page.locator(".metrics article").nth(3).locator("strong");
  await expect(enabled).toBeChecked();
  await expect(exchange).toHaveValue("35");
  await expect(count).not.toHaveText("0");
  await exchange.selectOption("53");
  await enabled.uncheck();
  await expect(exchange).toBeDisabled();
  await expect(exchange).toHaveValue("53");
  await expect(count).toHaveText("0");
  await expect(page.locator(".fast-wave-releases")).toContainText("all legs run sequentially");
  await enabled.check();
  await expect(exchange).toHaveValue("53");
  await exchange.selectOption("0");
  await expect(count).not.toHaveText("0");
  await exchange.selectOption("53");
  await enabled.uncheck();
  await page.getByLabel("Configuration preset").selectOption("three-waves");
  await page.getByRole("tab", { name: /Timing rules/ }).click();
  await expect(enabled).not.toBeChecked();
  await expect(exchange).toHaveValue("53");
  await page.getByLabel("Configuration name", { exact: true }).fill("Sequential fast waves");
  await page.getByRole("button", { name: "Save configuration", exact: true }).click();
  await page.reload();
  await page.getByLabel("Load configuration").selectOption({ label: "Sequential fast waves" });
  await page.getByRole("tab", { name: /Timing rules/ }).click();
  await expect(enabled).not.toBeChecked();
  await expect(exchange).toHaveValue("53");
  await page.setViewportSize({ width: 390, height: 844 });
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth + 1)).toBe(true);
  await page.locator(".fast-wave-releases").screenshot({ path: test.info().outputPath("fast-wave-releases-mobile.png") });
});
