import { test, expect } from "@playwright/test";
import { baseline, worstCaseIds } from "../src/data";

test("timing rules edit, evaluate, persist and draw readable chart markers", async ({ page }) => {
  const errors: string[] = [];
  page.on("pageerror", e => errors.push(e.message));
  await page.goto("./");
  await page.getByRole("tab", { name: /Timing rules/ }).click();
  await expect(page.getByLabel("Rule 1 time", { exact: true })).toHaveValue("19:00");
  await expect(page.getByLabel("Rule 2 day", { exact: true })).toHaveValue("2");
  await expect(page.locator(".chart-timing-rule")).toHaveCount(2);
  await page.getByLabel("Rule 1 time", { exact: true }).fill("01:00");
  await expect(page.locator(".timing-rule-summary summary")).toContainText("violated");
  await expect(page.locator(".deadline-violation")).toHaveCount(51);
  await page.locator(".timing-rule-summary summary").click();
  await expect(page.locator(".rule-results").first()).toContainText("Late by");
  await page.getByRole("button", { name: "Spread replay", exact: true }).click();
  await expect(page.locator(".timing-rule-summary")).toBeVisible();
  await expect(page.locator(".chart-timing-rule")).toHaveCount(0);
  await page.getByRole("button", { name: "Time / course chart", exact: true }).click();
  await page.getByRole("button", { name: "Exchanges", exact: true }).click();
  await page.getByLabel("Chart zoom").fill("2");
  await expect(page.locator(".chart-timing-rule")).toHaveCount(2);
  await page.locator(".trajectory").screenshot({ path: test.info().outputPath("timing-chart-desktop.png") });
  await page.getByRole("button", { name: "+ Add timing rule", exact: true }).click();
  await page.getByLabel("Rule 3 time", { exact: true }).fill("01:00");
  const labels = await page.locator(".chart-timing-rule text").evaluateAll(nodes => nodes.map(n => n.getAttribute("y")));
  expect(new Set(labels).size).toBe(3);
  expect(Math.min(...labels.map(Number))).toBeGreaterThanOrEqual(32);
  await page.getByLabel("Configuration preset").selectOption("three-waves");
  await page.getByRole("tab", { name: /Timing rules/ }).click();
  await expect(page.getByLabel("Rule 1 time", { exact: true })).toHaveValue("01:00");
  await page.getByLabel("Configuration name", { exact: true }).fill("Timing checks");
  await page.getByRole("button", { name: "Save configuration", exact: true }).click();
  await page.reload();
  await page.getByLabel("Load configuration").selectOption({ label: "Timing checks" });
  await page.getByRole("tab", { name: /Timing rules/ }).click();
  await expect(page.getByLabel("Rule 3 time", { exact: true })).toHaveValue("01:00");
  await page.getByLabel("Enable timing rule 1").uncheck();
  await expect(page.locator(".chart-timing-rule")).toHaveCount(2);
  await page.getByRole("button", { name: "Remove timing rule 3", exact: true }).click();
  await page.getByLabel("Rule 2 exchange", { exact: true }).selectOption("71");
  await expect(page.getByLabel("Rule 2 type", { exact: true })).toHaveValue("clear-by");
  await page.getByLabel("Rule 2 exchange", { exact: true }).selectOption("0");
  await expect(page.getByLabel("Rule 2 type", { exact: true })).toHaveValue("depart-after");
  await page.setViewportSize({ width: 390, height: 844 });
  await expect(page.getByLabel("Rule 2 time", { exact: true })).toBeVisible();
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth + 1)).toBe(true);
  await page.locator('.timing-rule-list').screenshot({ path: test.info().outputPath("timing-editor-mobile.png") });
  expect(errors).toEqual([]);
});

test("opening holds hypothetical teams and disabling it removes the hold", async ({ page }) => {
  const s = baseline([worstCaseIds.fastest]);
  s.worstCaseTeams.fastest.mode = "flat";
  s.worstCaseTeams.fastest.flatPace = 300;
  await page.goto("./");
  await page.getByLabel("Import configuration JSON").setInputFiles({ name: "fast.json", mimeType: "application/json", buffer: Buffer.from(JSON.stringify(s)) });
  await page.getByRole("tab", { name: /Timing rules/ }).click();
  await expect(page.locator(".timing-rule-editor").nth(1)).toContainText("1 team held");
  await page.locator(".timing-rule-summary summary").click();
  await expect(page.locator(".rule-results")).toContainText("D2 06:00");
  await page.getByLabel("Enable timing rule 2").uncheck();
  await expect(page.locator(".timing-rule-summary summary")).toContainText("0 teams held");
  await page.getByRole("tab", { name: /Historical field/ }).click();
  await page.getByLabel("Include Worst-case fastest", { exact: true }).uncheck();
  await expect(page.locator(".timing-rule-summary summary")).toContainText("Not evaluated");
});
