import { test, expect } from "@playwright/test";
import { worstCaseIds } from "../src/data";

test("custom teams can be edited, included, visualized and retained by presets", async ({ page }) => {
  const errors: string[] = [];
  page.on("pageerror", e => errors.push(e.message));
  await page.goto("./");
  await page.getByRole("tab", { name: /Historical field/ }).click();
  const fast = page.getByLabel("Include Worst-case fastest", { exact: true });
  const slow = page.getByLabel("Include Worst-case slowest", { exact: true });
  await expect(fast).not.toBeChecked();
  await expect(slow).not.toBeChecked();
  const overall = page.getByLabel("Worst-case fastest overall pace", { exact: true });
  const firstBin = page.getByLabel("Worst-case fastest legs 1–14", { exact: true });
  await expect(overall).toHaveValue("8:06");
  await expect(page.getByLabel("Worst-case slowest overall pace", { exact: true })).toHaveValue("14:10");
  const before = await firstBin.inputValue();
  await overall.fill("9:06");
  await overall.press("Enter");
  await expect(firstBin).not.toHaveValue(before);
  const customBin = await firstBin.inputValue();
  await page.getByLabel("Worst-case fastest pace mode").selectOption("flat");
  await overall.fill("10:00");
  await overall.press("Enter");
  await page.getByLabel("Worst-case fastest pace mode").selectOption("bins");
  await expect(firstBin).toHaveValue(customBin);
  await expect(overall).toHaveValue("9:06");
  await overall.fill("0:01");
  await overall.press("Enter");
  await expect(page.getByRole("alert")).toContainText("Last valid pace");
  await overall.press("Escape");
  await expect(overall).toHaveValue("9:06");
  await fast.check();
  await slow.check();
  await page.getByRole("button", { name: "Clear all", exact: true }).click();
  await expect(fast).toBeChecked();
  await expect(slow).toBeChecked();
  await page.getByLabel("Highlight team", { exact: true }).selectOption(worstCaseIds.fastest);
  await expect(page.locator(".timing-detail")).toContainText("Worst-case fastest");
  await page.getByRole("checkbox", { name: "2026 baseline", exact: true }).check();
  await page.getByLabel("Configuration preset").selectOption("three-waves");
  await page.getByRole("tab", { name: /Historical field/ }).click();
  await expect(overall).toHaveValue("9:06");
  await expect(fast).toBeChecked();
  await page.getByRole("button", { name: "Reset Worst-case fastest to historical defaults" }).click();
  await expect(overall).toHaveValue("8:06");
  await expect(fast).toBeChecked();
  await page.getByRole("button", { name: "Spread replay", exact: true }).click();
  await expect(page.locator(".replay-marker")).toHaveCount(2);
  await page.getByLabel("Highlight replay team").selectOption(worstCaseIds.fastest);
  await expect(page.locator(".replay-detail")).toContainText("Hypothetical");
  await page.getByLabel("Configuration name", { exact: true }).fill("Frontier test");
  await page.getByRole("button", { name: "Save configuration", exact: true }).click();
  const exportEvent = page.waitForEvent("download");
  await page.getByRole("button", { name: "↓ JSON", exact: true }).click();
  const file = test.info().outputPath("frontier.json");
  await (await exportEvent).saveAs(file);
  await page.getByRole("tab", { name: /Historical field/ }).click();
  await overall.fill("9:00");
  await overall.press("Enter");
  await page.getByRole("button", { name: "Duplicate", exact: true }).click();
  await page.getByLabel("Load configuration").selectOption({ label: "Frontier test" });
  await page.getByRole("tab", { name: /Historical field/ }).click();
  await expect(overall).toHaveValue("8:06");
  await page.getByLabel("Load configuration").selectOption({ label: "Frontier test copy" });
  await page.getByRole("tab", { name: /Historical field/ }).click();
  await expect(overall).toHaveValue("9:00");
  await page.getByLabel("Import configuration JSON").setInputFiles(file);
  await page.getByRole("tab", { name: /Historical field/ }).click();
  await expect(overall).toHaveValue("8:06");
  await expect(fast).toBeChecked();
  await page.screenshot({ path: test.info().outputPath("worst-case-desktop.png"), fullPage: true });
  await page.setViewportSize({ width: 390, height: 844 });
  await expect(overall).toBeVisible();
  await page.screenshot({ path: test.info().outputPath("worst-case-mobile.png"), fullPage: true });
  expect(errors).toEqual([]);
});
